-- Extend BusinessStatus with PENDING / REJECTED
ALTER TYPE "BusinessStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "BusinessStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

-- Extend AuditAction with LISTING_APPROVED / LISTING_REJECTED
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LISTING_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LISTING_REJECTED';
